"""empty message

Revision ID: 492bd17e4ee3
Revises: ceda9763ba30
Create Date: 2022-10-25 04:16:09.296717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '492bd17e4ee3'
down_revision = 'ceda9763ba30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
